Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name= "accounts"
urlpatterns = [
    path('login/', views.login_user, name="login"),
    path('logout/',views.logout_user, name="logout"),
    path('register/', views.user_registration, name= "register"),
    path('home/', views.home, name="home"),
    path('checkout/', views.checkout, name="checkout")
]

accounts/models.py
from django.db import models

class Product(models.Model):
    product_id = models.AutoField
    product_name = models.CharField(max_length=100, default = "")
    tagline = models.CharField(max_length=100, default = "")
    mrp = models.IntegerField(default=0)
    sp = models.IntegerField(default=0)
    Discount = models.IntegerField(default=0)
    image = models.ImageField(upload_to="accounts/img", default="")

    def __str__(self):
        return self.product_name


class Orders(models.Model):
    order_id = models.AutoField(primary_key=True)
    items_json= models.CharField(max_length=2000, default = "")
    name = models.CharField(max_length=90, default = "")
    email = models.CharField(max_length=100, default = "")
    address = models.CharField(max_length=200, default = "")
    city = models.CharField(max_length=100, default = "")
    state = models.CharField(max_length=100, default = "")
    zip_code = models.CharField(max_length=100, default=0)
    phone = models.CharField(max_length=100, default = 0)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class UserRegistrationForm(forms.Form):
    username = forms.CharField(label="Username", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(label="Email", max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label="password", max_length=100, widget = forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label="Confirm password", max_length=100, widget = forms.PasswordInput(attrs={'class':'form-control'}))
    
    def clean_email(self):
        email = self.cleaned_data['email']
        qs = User.objects.filter(email=email)
        if qs.exists():
              raise ValidationError('Email already exist')
        return(email)

    def clean_username(self):
        username = self.cleaned_data['username']
        q = User.objects.filter(username=username)
        if q.exists():
              raise ValidationError('Username already exist')
        return(username)

    #it is used to show field error i.e. error will show above the field
    #def cleane_password2(self):
        #p1 = self.cleaned_data['password1']
        #p2 = self.cleaned_data['password2']
        #if p1 != p2:
            #raise ValidationError("password don't match")
        #return(p2)

    def clean(self):
        cleaned_data = super().clean()
        p1 = cleaned_data.get('password1')
        p2 = cleaned_data.get('password2')
        if p1 and p2:
            if p1 != p2:
                raise ValidationError('password Do Not Match')
        

accounts/views.py
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse
from .forms import UserRegistrationForm
from .models import Product, Orders

# Create your views here.


def login_user(request):
    if request.method == "POST":
        #print(request.POST)
        username = request.POST.get('username')
        #print(username)
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        #print(user)
        if user is not None:
            #print(request.GET)
            login(request, user)
            # return HttpResponseRedirect(reverse('home'))
            # return redirect('home')
            return redirect('accounts:home')
        else:
            messages.error(request, 'wrong authentication')
    return render(request, 'accounts/login.html', {})


def logout_user(request):
    logout(request)
    # return HttpResponseRedirect(reverse('home'))
    return redirect('accounts:login')

@login_required
def home(request):
    allproduct = Product.objects.all()
    #print(allproduct)
    params = {'product': allproduct}
    return render(request, 'accounts/home.html', params)


def user_registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            # print(request.POST)
            # print(form.cleaned_data)

            # comment these these thing because i don't want to create new user every time
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            email = form.cleaned_data['email']
            user = User.objects.create_user(
                username=username, email=email, password=password)
            # print(user)
            messages.success(
                request, 'thanks for register {}'.format(user.username))
            # return HttpResponseRedirect(reverse('accounts:login'))
            return redirect('accounts:login')
            print("form is valid ")
    else:
        form = UserRegistrationForm()

    return render(request, 'accounts/register.html', {'form': form})

@login_required
def checkout(request):
    if request.method=="POST":
        items_json = request.POST.get('itemjson', '')
        name=request.POST.get('name', '')
        email=request.POST.get('email', '')
        address=request.POST.get('address1', '') + " " + request.POST.get('address2', '')
        city=request.POST.get('city', '')
        state=request.POST.get('state', '')
        zip_code=request.POST.get('zip_code', '')
        phone=request.POST.get('phone', '')
        order = Orders(items_json=items_json, name=name, email=email, address= address, city=city, state=state, zip_code=zip_code, phone=phone)
        order.save()
        thank = True
        id = order.order_id
        return render(request, 'accounts/checkout.html',{'thank':thank, 'id':id})
    return render(request, 'accounts/checkout.html')

accounts/templates/accounts/base.html
{% load static %}
<html lang="en">

<head>
    <title>pollme</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type='text/css' href="{% static 'css/main.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
        integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"
        integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG"
        crossorigin="anonymous"></script>

    <style>


    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Ecommerce</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
            aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'accounts:home' %}">Home <span
                        class="sr-only">(current)</span></a>
            </div>

            <div class="navbar-nav">
                <a class="nav-item nav-link active" href="{% url 'accounts:checkout' %}">Checkout </a>
            </div>

            <button type="button" class="btn btn-secondary" id="popcart" data-container="body"
                data-toggle="popover" data-placement="bottom" data-content="Bottom popover">
                Cart(<span id="cart">0</span>)
            </button>

        </div>
        <div class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Logout</a>
            {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Login</a>
            {% endif %}
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
</body>

</html>

accounts/templates/accounts/checkout.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="container">
    <div class="col my-4">
        <h2>Step 1 : Checkout - Review Your Cart Item</h2>
        <div class="my-4">
            <ul class="list-group" id="items">

            </ul>
        </div>
    </div>
    <div class="col my-2">
        <h2>Step 2 - Enter Address & Other Details</h2>
        <form class="row g-3" method="post" action="/accounts/checkout/">
            {% csrf_token %}
            <input type="hidden" name="itemjson" id="itemjson">
            <div class="col-md-6">
                <label for="inputname" class="form-label">Name</label>
                <input type="text" class="form-control" id="name" name = "name" placeholder="Name">
            </div>
            <div class="col-md-6">
                <label for="inputEmail4" class="form-label">Email</label>
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
            </div>

            <div class="col-12">
                <label for="inputAddress" class="form-label">Address </label>
                <input type="text" class="form-control" id="address1" name = "address1" placeholder="1234 Main St">
            </div>
            <div class="col-12">
                <label for="inputAddress2" class="form-label">Address Line 2</label>
                <input type="text" class="form-control" id="address2" name = "address2" placeholder="Apartment, studio, or floor">
            </div>
            <div class="col-md-6">
                <label for="inputCity" class="form-label">City</label>
                <input type="text" class="form-control" id="city" name = "city" placeholder="Enter City">
            </div>
            <div class="col-md-4">
                <label for="inputState" class="form-label">State</label>
                <input type="text" class="form-control" id="state" name = "state" placeholder="Enter State">
            </div>
            <div class="col-md-2">
                <label for="inputZip" class="form-label">Zip</label>
                <input type="text" class="form-control" id="zip" name = "zip_code" placeholder="Enter Zip">
            </div>
            <div class="col">
                <label for="inputphone" class="form-label">Phone No.</label>
                <input type="tel" class="form-control" id="phone" name = "phone" placeholder="Phone No.">
            </div>
            <div class="col-12 my-2">
                <button type="submit" class="btn btn-primary">Place Order</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    if (localStorage.getItem('cart') == null) {
        var cart = {};
    }
    else {
        cart = JSON.parse(localStorage.getItem('cart'));
    }
    console.log(cart);
    var sum=0;
    if ($.isEmptyObject(cart)) {
        mystr = `<p>Your cart is empty, Please add some items !</p>`
        $('#items').append(mystr);
    }
    else {
        for (item in cart) {
            let name = cart[item][1];
            let qty = cart[item][0];
            sum = sum+qty;
            mystr = `<li class="list-group-item d-flex justify-content-between align-items-center">
                    ${name}
                    <span class="badge bg-primary rounded-pill">${qty}</span>
                </li>`
            $('#items').append(mystr);
        }
    }
    document.getElementById('cart').innerHTML = sum;
    $('#itemjson').val(JSON.stringify(cart));
    {% if thank %}
    alert('Thanks for ordering. your order id id {{id}}')
    localStorage.clear();
    {% endif %}
</script>

{% endblock %}

accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}

{% block content %}


<div class="product-items">
    <!-- single product -->
    {% for pro in product %}
    <div class="product">
        <div class="product-content">
            <div class="product-img">
                <img src='/image/{{pro.image}}' alt="product image">
            </div>
            <div class="product-btns">
                <button id = "pr{{pro.id}}" type="button" class="btn-cart cart"> add to cart
                    <span><i class="fas fa-plus"></i></span>
                </button>
                <button type="button" class="btn-buy"> buy now
                    <span><i class="fas fa-shopping-cart"></i></span>
                </button>
            </div>
        </div>

        <div class="product-info">
            <div class="product-info-top">
                <h2 class="sm-title"><b>{{pro.tagline}}</b></h2>
            </div>
            <a href="#" class="product-name"id = "namepr{{pro.id}}">{{pro.product_name}}</a>
            <p class="product-price">Rs {{pro.mrp}}</p>
            <p class="product-price">Rs {{pro.sp}} </p>
        </div>

        <div class="off-info">
            <h2 class="sm-title">{{pro.Discount}}% off</h2>
        </div>
    </div>
    {% endfor %}
</div>




    <div class = "product-collection">
        <div class = "container">
            <div class = "product-collection-wrapper">
                <!-- product col left -->
                <div class = "product-col-left flex">
                    <div class = "product-col-content">
                        <h2 class = "sm-title">men's shoes </h2>
                        <h2 class = "md-title">men's collection </h2>
                        <p class = "text-light">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestiae consequatur facilis eligendi quibusdam voluptatibus exercitationem autem voluptatum, beatae architecto odit, quisquam repellat. Deleniti, architecto ab.</p>
                        <button type = "button" class = "btn-dark">Shop now</button>
                    </div>
                </div>

                <!-- product col right -->
                <div class = "product-col-right">
                    <div class = "product-col-r-top flex">
                        <div class = "product-col-content">
                            <h2 class = "sm-title">women's dresses </h2>
                            <h2 class = "md-title">women's collection </h2>
                            <p class = "text-light">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestiae consequatur facilis eligendi quibusdam voluptatibus exercitationem autem voluptatum, beatae architecto odit, quisquam repellat. Deleniti, architecto ab.</p>
                            <button type = "button" class = "btn-dark">Shop now</button>
                        </div>
                    </div>

                    <div class = "product-col-r-bottom">
                        <!-- left -->
                        <div class = "flex">
                            <div class = "product-col-content-sale1 ">
                                <h2 class = "sm-title"><h5>summer sale</h5> </h2>
                                <h2 class = "md-title">Extra 50% Off </h2>
                                <p class = "text-light"><h3>New Collection</h2></p>
                                <button type = "button" class = "btn-dark">Shop now</button>
                            </div>
                        </div>
                        <!-- right -->
                        <div class = "flex">
                            <div class = "product-col-content">
                                <p class = "text-light"><h2>Best Product</h2></p>
                                <h2 class = "sm-title">shoes </h2>
                                <h2 class = "md-title">best sellers </h2>
                                <button type = "button" class = "btn-dark">Shop now</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock %}


    {% block js %}
    <script>
        console.log('working');
        if(localStorage.getItem('cart')==null){
            var cart = {};
        }
        else
        {
            cart = JSON.parse(localStorage.getItem('cart'));
            document.getElementById('cart').innerHTML = Object.keys(cart).length;
        }
        $('.cart').click(function(){
            console.log('clicked');
            var idstr = this.id.toString();
            console.log(idstr);
            if(cart[idstr]!=undefined)
            {
                cart[idstr][0] = cart[idstr][0]+1;
            }
            else
            {
                qty = 1;
                name = document.getElementById('name' + idstr).innerHTML;
                cart[idstr] = [qty, name];
            }
            console.log(cart);
            localStorage.setItem('cart', JSON.stringify(cart));
            document.getElementById('cart').innerHTML = Object.keys(cart).length;
        });
        $('#popcart').popover('show');
        document.getElementById("popcart").setAttribute('data-content', '<h5>Cart for your item in my shopping cart</h5>');
    </script>
    {% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block content %}

<div class="container login">

    <div class="row">
        <div class="col-md-6 offset-md-3">
            {% if messages %}
                <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
            <form action="" method="post">
                <div class="form-group">
                    {% csrf_token %}
                  <label for="Username">Username</label>
                  <input type="text" class="form-control" name="username" placeholder="Enter email">
                </div>
                <div class="form-group">
                  <label for="Password">Password</label>
                  <input type="password" class="form-control" name="password" placeholder="Enter Password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            <p>Need an account? <a href="{% url 'accounts:register' %}">Register Here!</a></p>
        </div>
    </div>

</div>

{% endblock %}